### PR TITLE
ES6 & Added Support for different thumbnail & preview images

### PR DESCRIPTION
**Pull request by haideralipunjabi**
Hi

I renamed all the `var` to `let` & added support for different thumbnail & preview images, i.e, if `data-previewer` attribute is defined, the library will use that to load the preview. It is helpful when you only want to have the thumbnail smaller in size to the actual preview.

I didn't add about it in the README, or change the example or the version data.

Usage 
```html
< img src="thumbnail-src" data-previewer="preview-src" class="preview-image">
```

### CODE REVIEW

**Comment by ajayns** [comment]
Hey Haider, Thank you for the PR!

About ES6, this isn't really a migration by just renaming var to let, a lot more could be done imo. But the feature you've added definitely looks useful so please go ahead by adding the changes to the Readme as well. 

Also, are there any breaking changes? Does it fallback to the thumbnail image itself if `data-previewer` isn't specified?

**Comment by haideralipunjabi** [comment]
Yes it falls back to if `data-previewer` isn't specified. I will add the changed to README soon

**Comment by ajayns** [comment]
Also, unless you're planning on doing a full ES6 refactor along with build config, I'd prefer we keep it pre-es6 itself for maximum compatibility

**Comment by haideralipunjabi** [comment]
Ok, I am done

**Comment by ajayns** [comment]
Thanks a bunch for your contribution! @haideralipunjabi

**Pull request merged**
